module.exports={
  bloomingdales:{
    entry: 'https://www.bloomingdales.com',
    brandName: "Bloomingdale's",
    searchInput: '.aboveNavSearchBox',
    product: '.productThumbnail',
    imgTag: 'img',
    imgUrlModifier: 'https://www.bloomingdales.com',
    nameTag: '.productDescription',
    priceTag: '.regular',
  },
  abercrombie:{
    entry: 'https://www.abercrombie.com/shop/us',
    brandName: "Abercrombie",
    searchInput: '.rs-nav-icon--search',
    product: '.product-card',
    imgTag: '.product-card_img',
    imgUrlModifier: 'https:',
    nameTag: '.product-info-item-name',
    priceTag: '.product-info-item-price',
  },
  zara:{
    entry: 'https://www.zara.com/us/en/search',
    brandName: "Zara",
    searchInput: '#search-term',
    product: '._product',
    imgTag: '._img',
    imgUrlModifier: 'https:',
    nameTag: '.product-info-item-name',
    priceTag: '.product-info-item-price',
  },
  macys:{
    entry: 'https://www.macys.com',
    brandName: "Macy's",
    searchInput: '#globalSearchInputField',
    product: '.productThumbnail',
    imgTag: 'img',
    imgUrlModifier: 'https://www.macys.com',
    nameTag: '.productDescription',
    priceTag: '.regular',
  },
}